name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/JJBJJ/PyramidStore.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout main
          git merge upstream/main

      - name: Generate py.json
        run: |
          python generate_pyjson.py
          git add py.json
          git commit -m "chore: update py.json" || true
          git push origin main 
